### ISSUE TITLE
Tests needed for demes models

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#816]
#814 implies that we need some testing that probes a bit more deeply into what is happening during a simulation.   This issue is a thread to start collecting them.  Rather than writing tests, we should uncover patterns in what needs testing so that we an write richer tests w/o as much copy paste of boiler plate.

**Comment by molpopgen** [comment]
[From](https://popsim-consortium.github.io/demes-spec-docs/main/tutorial.html#continuous-migration) the demes tutorial.  We should scale this one down and make sure there's no ancestral/derived overlap:

```yaml
time_units: generations
demes:
  - name: X
    epochs:
      - end_time: 1000
        start_size: 2000
  - name: A
    ancestors: [X]
    epochs:
      - start_size: 2000
  - name: B
    ancestors: [X]
    epochs:
      - start_size: 2000
migrations:
  - source: A
    dest: B
    rate: 1e-4
```
